### ISSUE TITLE
Genome graphs

### ISSUE THREAD

**Issue by husamia** [bajicv/mtDNA_nomenclutter#1]
Have you explored the recently proposed genome graph representations of mt genome and it's implications?

**Comment by bajicv** [comment]
Hi @husamia! I haven't explored it yet, but I think it's definitely worth of looking into it in more detail. I also find the output of [HaploCart](https://github.com/grenaud/vgan) very interesting and useful (i.e. Haplocart Posterior File that provides the information about different clades, posterior probabilities, and tree depths)!

In our study we are mostly focusing on the effect of secondary haplogroup groupings (i.e. those that come after haplogroup calling) and on the influence of mtDNA nomenclature on our decisions when making those secondary haplogorup groupings.

If you (or anyone else reading this) have any more ideas, suggestions, or questions (that are not necessarily related to the code itself), please feel free to use the [Discussion forum](https://github.com/bajicv/mtDNA_nomenclutter/discussions)! I think it's important that we all brainstorm and try finding a solution that would work for everyone. :)
